export const fixManifestFiles = [
  {
    createdAt: 'Jun 19, 2020, 12:31:37 PM',
    form_relation: '',
    id: '52',
    identifier: 'test-form-1.json',
    isDraft: false,
    isJsonValidator: true,
    jursdiction: '',
    label: 'test form',
    module: '',
    version: '1.0.26',
  },
  {
    createdAt: 'Jun 19, 2020, 4:23:22 PM',
    form_relation: '',
    id: '53',
    identifier: 'reveal-test-file.json',
    isDraft: false,
    isJsonValidator: true,
    jursdiction: '',
    label: 'test publish',
    module: '',
    version: '1.0.27',
  },
];
