/** Fixtures for tests */
export const data = [
  {
    '%': 0.88,
    A1: 80,
    A2: 40,
    Adherence: 0.94,
    B1: 5,
    B2: 2,
    Number: 75,
    Total: 132,
    name: 'Province 1',
    parent: null,
    type: 'Province',
  },
  {
    '%': 1.0,
    A1: 63,
    A2: 30,
    Adherence: 1.0,
    B1: 2,
    B2: 1,
    Number: 63,
    Total: 96,
    name: 'Province 2',
    parent: null,
    type: 'Province',
  },
  {
    '%': 0.67,
    A1: 76,
    A2: 20,
    Adherence: 0.79,
    B1: 2,
    B2: 0,
    Number: 51,
    Total: 98,
    name: 'Province 3',
    parent: null,
    type: 'Province',
  },
  {
    '%': 0.87,
    A1: 60,
    A2: 30,
    Adherence: 0.98,
    B1: 14,
    B2: 3,
    Number: 52,
    Total: 107,
    name: 'Province 4',
    parent: null,
    type: 'Province',
  },
  {
    '%': 0.83,
    A1: 24,
    A2: 9,
    Adherence: 0.94,
    B1: 2,
    B2: 3,
    Number: 20,
    Total: 38,
    name: 'District 1',
    parent: 'Province 1',
    type: 'District',
  },
  {
    '%': 0.81,
    A1: 16,
    A2: 15,
    Adherence: 1.0,
    B1: 1,
    B2: 1,
    Number: 13,
    Total: 33,
    name: 'District 2',
    parent: 'Province 1',
    type: 'District',
  },
  {
    '%': 0.55,
    A1: 22,
    A2: 5,
    Adherence: 0.95,
    B1: 1,
    B2: 0,
    Number: 12,
    Total: 28,
    name: 'District 3',
    parent: 'Province 1',
    type: 'District',
  },
  {
    '%': 0.95,
    A1: 20,
    A2: 7,
    Adherence: 0.98,
    B1: 0,
    B2: 1,
    Number: 19,
    Total: 28,
    name: 'District 4',
    parent: 'Province 1',
    type: 'District',
  },
  {
    '%': 1.0,
    A1: 3,
    A2: 4,
    Adherence: 0.67,
    B1: 1,
    B2: 0,
    Number: 3,
    Total: 8,
    name: 'District 5',
    parent: 'Province 1',
    type: 'District',
  },
  {
    '%': 0.92,
    A1: 13,
    A2: 4,
    Adherence: 0.94,
    B1: 1,
    B2: 2,
    Number: 12,
    Total: 20,
    name: 'Canton 1',
    parent: 'District 1',
    type: 'Canton',
  },
  {
    '%': 0.6,
    A1: 5,
    A2: 3,
    Adherence: 1.0,
    B1: 1,
    B2: 1,
    Number: 3,
    Total: 10,
    name: 'Canton 2',
    parent: 'District 1',
    type: 'Canton',
  },
  {
    '%': 1.0,
    A1: 6,
    A2: 2,
    Adherence: 0.79,
    B1: 0,
    B2: 0,
    Number: 6,
    Total: 8,
    name: 'Canton 3',
    parent: 'District 1',
    type: 'Canton',
  },
  {
    '%': 0.5,
    A1: 2,
    A2: 2,
    Adherence: 0.8,
    B1: 1,
    B2: 0,
    Number: 1,
    Total: 5,
    name: 'Village 1',
    parent: 'Canton 1',
    type: 'Village',
  },
  {
    '%': 0.8,
    A1: 5,
    A2: 1,
    Adherence: 1.0,
    B1: 0,
    B2: 1,
    Number: 4,
    Total: 7,
    name: 'Village 2',
    parent: 'Canton 1',
    type: 'Village',
  },
  {
    '%': 0.5,
    A1: 6,
    A2: 1,
    Adherence: 0.75,
    B1: 0,
    B2: 1,
    Number: 3,
    Total: 8,
    name: 'Village 3',
    parent: 'Canton 1',
    type: 'Village',
  },
  {
    '%': 0.87,
    A1: 60,
    A2: 30,
    Adherence: 0.98,
    B1: 14,
    B2: 3,
    Number: 52,
    Total: 107,
    name: 'Foci Area 1',
    parent: 'Village 1',
    type: 'Foci Area',
  },
  {
    Adherence: 'Yes',
    lastVisit: '07/11/18',
    name: 'Foci Area 1',
    parent: 'Village 1',
    status: 'A1',
    type: 'Foci Area',
  },
  {
    Adherence: 'Yes',
    lastVisit: '09/04/18',
    name: 'Foci Area 2',
    parent: 'Village 1',
    status: 'A2',
    type: 'Foci Area',
  },
  {
    Adherence: 'No',
    lastVisit: '07/11/18',
    name: 'Foci Area 3',
    parent: 'Village 1',
    status: 'A1',
    type: 'Foci Area',
  },
  {
    Adherence: 'Yes',
    lastVisit: '23/11/18',
    name: 'Foci Area 4',
    parent: 'Village 1',
    status: 'B1',
    type: 'Foci Area',
  },
  {
    Adherence: 'Yes',
    lastVisit: '15/07/18',
    name: 'Foci Area 5',
    parent: 'Village 1',
    status: 'A2',
    type: 'Foci Area',
  },
];
