[template]
src = "config.js.tmpl"
dest = "/usr/src/web/config.js"
keys = [
  "/generate/sourcemap",
  "/skip/preflight/check",
  "/react/app/domain/name",
  "/react/app/website/name",
  "/react/app/theme/color",
  "/react/app/language",
  "/react/app/ga/code",
  "/react/app/enable/irs",
  "/react/app/enable/fi",
  "/react/app/enable/users",
  "/react/app/enable/assign",
  "/react/app/enable/about",
  "/react/app/enable/teams",
  "/react/app/enable/practitioners",
  "/react/app/enable/mda/point",
  "/react/app/enable/population/server/settings",
  "/react/app/enable/planning",
  "/react/app/enable/jurisdiction/metadata/upload",
  "/react/app/enable/structure/metadata/upload",
  "/react/app/enable/irs/performance/report",
  "/react/app/enable/config/form",
  "/react/app/disable/login/protection",
  "/react/app/enable/irs/mopup/reporting",
  "/react/app/enable/smc",
  "/react/app/superset/api/base",
  "/react/app/superset/api/endpoint",
  "/react/app/superset/max/records",
  "/react/app/superset/plans/slice",
  "/react/app/superset/goals/slice",
  "/react/app/superset/jurisdictions/slice",
  "/react/app/superset/structures/slice",
  "/react/app/superset/jurisdictions/data/slice",
  "/react/app/superset/plan/structure/pivot/slice",
  "/react/app/superset/plans/table/slice",
  "/react/app/superset/tasks/slice",
  "/react/app/superset/jurisdiction/events/slice",
  "/react/app/superset/irs/reporting/jurisdictions/data/slices",
  "/react/app/superset/irs/reporting/structures/data/slice",
  "/react/app/superset/irs/reporting/plans/slice",
  "/react/app/superset/irs/reporting/jurisdictions/focus/area/level",
  "/react/app/superset/irs/reporting/jurisdictions/columns",
  "/react/app/superset/irs/reporting/focus/areas/columns",
  "/react/app/superset/irs/reporting/indicator/stops",
  "/react/app/superset/irs/reporting/indicator/rows",
  "/react/app/superset/mda/point/reporting/plans/slice",
  "/react/app/superset/mda/point/reporting/jurisdictions/data/slices",
  "/react/app/superset/mda/point/location/report/data/slice",
  "/react/app/superset/mda/point/child/report/data/slice",
  "/react/app/superset/mda/point/reporting/jurisdictions/focus/area/level",
  "/react/app/enable/opensrp/oauth",
  "/react/app/opensrp/client/id",
  "/react/app/opensrp/access/token/url",
  "/react/app/opensrp/authorization/url",
  "/react/app/opensrp/user/url",
  "/react/app/opensrp/api/base/url",
  "/react/app/opensrp/oauth/state",
  "/react/app/enable/onadata/oauth",
  "/react/app/gisida/mapbox/token",
  "/react/app/digital/globe/connect/id",
  "/react/app/date/format",
  "/react/app/default/plan/duration/days",
  "/react/app/plan/version",
  "/react/app/irs/plan/countries",
  "/react/app/env",
  "/react/app/opensrp/logout/url",
  "/react/app/express/oauth/logout/url",
  "/react/app/express/oauth/get/state/url",
  "/react/app/backend/active",
  "/react/app/version",
  "/react/app/name",
  "/react/app/navbar/brand/img/src",
  "/react/app/reveal/brand/img/src",
  "/react/app/enable/dynamic/mda",
  "/react/app/superset/dynamic/mda/reporting/plans/slice",
  "/react/app/superset/dynamic/mda/reporting/jurisdictions/data/slices",
  "/react/app/superset/dynamic/mda/reporting/jurisdictions/columns",
  "/react/app/superset/dynamic/mda/reporting/focus/areas/columns",
  "/react/app/superset/dynamic/mda/reporting/jurisdictions/focus/area/level",
  "/react/app/enable/home/manage/plans/link",
  "/react/app/enable/home/planning/view/link",
  "/react/app/superset/irs/district/performance/report/slice",
  "/react/app/superset/irs/data/collectors/performance/report/slice",
  "/react/app/superset/irs/sop/performance/report/slice",
  "/react/app/superset/irs/sop/by/date/performance/report/slice",
  "/react/app/enable/irs/lite",
  "/react/app/superset/irs/lite/reporting/jurisdictions/data/slices",
  "/react/app/superset/irs/lite/reporting/jurisdictions/focus/area/level",
  "/react/app/superset/irs/lite/reporting/jurisdictions/focus/area/slice",
  "/react/app/superset/irs/lite/reporting/jurisdictions/columns",
  "/react/app/superset/irs/lite/reporting/focus/areas/columns",
  "/react/app/superset/irs/lite/reporting/indicator/stops",
  "/react/app/superset/irs/lite/reporting/indicator/rows",
  "/react/app/superset/irs/lite/reporting/jurisdictions/data/slice",
  "/react/app/superset/irs/lite/reporting/structures/data/slice",
  "/react/app/superset/irs/lite/reporting/plans/slice",
  "/react/app/superset/irs/lite/reporting/jurisdictions/data/slice",
  "/react/app/superset/irs/lite/reporting/structures/data/slice",
  "/react/app/superset/irs/lite/reporting/plans/slice",
  "/react/app/practitioner/request/page/size",
  "/react/app/enable/default/plan/user/filter",
  "/react/app/superset/smc/reporting/focus/areas/columns",
  "/react/app/superset/smc/reporting/jurisdictions/columns",
  "/react/app/superset/smc/reporting/jurisdictions/focus/area/level",
  "/react/app/superset/smc/reporting/plans/slice",
  "/react/app/superset/smc/reporting/jurisdictions/data/slices",
  "/react/app/superset/smc/reporting/structures/data/slice",
  "/react/app/superset/smc/reporting/indicator/stops",
  "/react/app/superset/smc/reporting/indicator/rows",
  "/react/app/check/session/expiry/status",
  "/react/app/enable/mda/lite",
  "/react/app/superset/mda/lite/reporting/plans/slice",
  "/react/app/superset/mda/lite/reporting/jurisdictions/data/slices",
  "/react/app/superset/mda/lite/reporting/supervisors/data/slice",
  "/react/app/superset/mda/lite/reporting/cdd/data/slice",
  "/react/app/superset/mda/lite/reporting/ward/slice",
  "/react/app/superset/mda/lite/reporting/ward/geojson/slice",
  "/react/app/show/map/at/jurisdiction/level",
  "/react/app/clients/list/batch/size",
  "/react/app/plan/team/assignment/expiry/years",
  "/react/app/superset/oauth/state",
]
