const props = {
  className: 'form-control',
  dateFormat: 'yyyy-MM-dd',
  disabled: false,
  field: {
    name: 'start',
    onChange: jest.fn(),
    value: '2019-08-05T10:17:17.765Z',
  },
  form: {
    dirty: false,
    errors: {},
    initialValues: {
      activities: [
        {
          actionCode: 'Case Confirmation',
          actionDescription: 'Confirm the index case',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Case Confirmation',
          goalDescription: 'Confirm the index case',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 1,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'RACD Register Family',
          actionDescription:
            'Register all families & family members in all residential structures enumerated (100%) within the operational area',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Family Registration',
          goalDescription:
            'Register all families & family members in all residential structures enumerated (100%) within the operational area',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 100,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'Blood Screening',
          actionDescription:
            'Visit all residential structures (100%) within a 1 km radius of a confirmed index case and test each registered person',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Blood screening',
          goalDescription:
            'Visit all residential structures (100%) within a 1 km radius of a confirmed index case and test each registered person',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 100,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'Bednet Distribution',
          actionDescription:
            'Visit 100% of residential structures in the operational area and provide nets',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Bednet Distribution',
          goalDescription:
            'Visit 100% of residential structures in the operational area and provide nets',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 100,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'Larval Dipping',
          actionDescription:
            'Perform a minimum of three larval dipping activities in the operational area',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Larval Dipping',
          goalDescription:
            'Perform a minimum of three larval dipping activities in the operational area',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 3,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'Mosquito Collection',
          actionDescription:
            'Set a minimum of three mosquito collection traps and complete the mosquito collection process',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Mosquito Collection',
          goalDescription:
            'Set a minimum of three mosquito collection traps and complete the mosquito collection process',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 3,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'BCC',
          actionDescription: 'Conduct BCC activity',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Behaviour Change Communication',
          goalDescription: 'Complete at least 1 BCC activity for the operational area',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 1,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
      ],
      caseNum: '',
      date: '2019-08-05T10:17:17.765Z',
      end: '2019-08-25T10:17:17.765Z',
      identifier: '',
      interventionType: 'FI',
      jurisdictions: [
        {
          id: '',
          name: '',
        },
      ],
      name: '',
      start: '2019-08-05T10:17:17.765Z',
      status: 'draft',
      title: '',
      version: '1',
    },
    isSubmitting: false,
    isValid: false,
    isValidating: false,
    submitCount: 0,
    touched: {},
    validateOnBlur: true,
    validateOnChange: true,
    values: {
      activities: [
        {
          actionCode: 'Case Confirmation',
          actionDescription: 'Confirm the index case',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Case Confirmation',
          goalDescription: 'Confirm the index case',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 1,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'RACD Register Family',
          actionDescription:
            'Register all families & family members in all residential structures enumerated (100%) within the operational area',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Family Registration',
          goalDescription:
            'Register all families & family members in all residential structures enumerated (100%) within the operational area',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 100,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'Blood Screening',
          actionDescription:
            'Visit all residential structures (100%) within a 1 km radius of a confirmed index case and test each registered person',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Blood screening',
          goalDescription:
            'Visit all residential structures (100%) within a 1 km radius of a confirmed index case and test each registered person',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 100,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'Bednet Distribution',
          actionDescription:
            'Visit 100% of residential structures in the operational area and provide nets',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Bednet Distribution',
          goalDescription:
            'Visit 100% of residential structures in the operational area and provide nets',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 100,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'Larval Dipping',
          actionDescription:
            'Perform a minimum of three larval dipping activities in the operational area',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Larval Dipping',
          goalDescription:
            'Perform a minimum of three larval dipping activities in the operational area',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 3,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'Mosquito Collection',
          actionDescription:
            'Set a minimum of three mosquito collection traps and complete the mosquito collection process',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Mosquito Collection',
          goalDescription:
            'Set a minimum of three mosquito collection traps and complete the mosquito collection process',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 3,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
        {
          actionCode: 'BCC',
          actionDescription: 'Conduct BCC activity',
          actionIdentifier: '',
          actionReason: 'Investigation',
          actionTitle: 'Behaviour Change Communication',
          goalDescription: 'Complete at least 1 BCC activity for the operational area',
          goalDue: '2019-08-12T10:17:17.765Z',
          goalPriority: 'medium-priority',
          goalValue: 1,
          timingPeriodEnd: '2019-08-12T10:17:17.765Z',
          timingPeriodStart: '2019-08-05T10:17:17.765Z',
        },
      ],
      caseNum: '',
      date: '2019-08-05T10:17:17.765Z',
      end: '2019-08-25T10:17:17.765Z',
      identifier: '',
      interventionType: 'FI',
      jurisdictions: [
        {
          id: '',
          name: '',
        },
      ],
      name: '',
      start: '2019-08-05T10:17:17.765Z',
      status: 'draft',
      title: '',
      version: '1',
    },
  },
  id: 'start',
  required: true,
  type: 'date',
};

export default props;
