/** You can hard code variables that would have been
 * extracted from the environment here, and then mock
 * this file from your test file.
 * The goal is to have consistent test results
 */

export const SUPERSET_PLANS_SLICE = 0;
export type SUPERSET_PLANS_SLICE = typeof SUPERSET_PLANS_SLICE;

export const SUPERSET_MAX_RECORDS = 3000;
export type SUPERSET_MAX_RECORDS = typeof SUPERSET_MAX_RECORDS;

export const GISIDA_TIMEOUT = 3000;
export type GISIDA_TIMEOUT = typeof GISIDA_TIMEOUT;

export const GISIDA_MAPBOX_TOKEN = 'hunter2';
export type GISIDA_MAPBOX_TOKEN = typeof GISIDA_MAPBOX_TOKEN;

export const GISIDA_ONADATA_API_TOKEN = 'hunter2';
export type GISIDA_ONADATA_API_TOKEN = typeof GISIDA_ONADATA_API_TOKEN;

export const DIGITAL_GLOBE_CONNECT_ID = 'hunter2';
export type DIGITAL_GLOBE_CONNECT_ID = typeof DIGITAL_GLOBE_CONNECT_ID;

export const OPENSRP_API_BASE_URL = 'https://test.smartregister.org/opensrp/rest/';
export type OPENSRP_API_BASE_URL = typeof OPENSRP_API_BASE_URL;

export const PLAN_UUID_NAMESPACE = '1bb3c217-af1c-4749-b3df-4f6108582e3c';
export type PLAN_UUID_NAMESPACE = typeof PLAN_UUID_NAMESPACE;

export const ACTION_UUID_NAMESPACE = '1bb3c217-af1c-4749-b3df-4f6108582e3c';
export type ACTION_UUID_NAMESPACE = typeof ACTION_UUID_NAMESPACE;

export const GA_CODE = 'UA-154169046-1';
export type GA_CODE = typeof GA_CODE;

export const GA_ENV = 'test';
export type GA_ENV = typeof GA_ENV;

export const DEFAULT_PLAN_VERSION = '2';
export type DEFAULT_PLAN_VERSION = typeof DEFAULT_PLAN_VERSION;

export const SUPERSET_JURISDICTIONS_SLICE = 1;
export type SUPERSET_JURISDICTIONS_SLICE = typeof SUPERSET_JURISDICTIONS_SLICE;

export const SUPERSET_STRUCTURES_SLICE = 2;
export type SUPERSET_STRUCTURES_SLICE = typeof SUPERSET_STRUCTURES_SLICE;

export const SUPERSET_GOALS_SLICE = 3;
export type SUPERSET_GOALS_SLICE = typeof SUPERSET_GOALS_SLICE;

export const SUPERSET_TASKS_SLICE = 4;
export type SUPERSET_TASKS_SLICE = typeof SUPERSET_TASKS_SLICE;

export const SUPERSET_IRS_REPORTING_JURISDICTIONS_DATA_SLICES = '11,12';
export type SUPERSET_IRS_REPORTING_JURISDICTIONS_DATA_SLICES = typeof SUPERSET_IRS_REPORTING_JURISDICTIONS_DATA_SLICES;
export const SUPERSET_IRS_REPORTING_PLANS_SLICE = '13';
export type SUPERSET_IRS_REPORTING_PLANS_SLICE = typeof SUPERSET_IRS_REPORTING_PLANS_SLICE;
export const SUPERSET_IRS_REPORTING_STRUCTURES_DATA_SLICE = '14';
export type SUPERSET_IRS_REPORTING_STRUCTURES_DATA_SLICE = typeof SUPERSET_IRS_REPORTING_STRUCTURES_DATA_SLICE;
export const SUPERSET_IRS_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = '4';
export type SUPERSET_IRS_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = typeof SUPERSET_IRS_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL;
export const SUPERSET_IRS_REPORTING_JURISDICTIONS_COLUMNS = 'zambiaJurisdictions2019';
export type SUPERSET_IRS_REPORTING_JURISDICTIONS_COLUMNS = typeof SUPERSET_IRS_REPORTING_JURISDICTIONS_COLUMNS;
export const SUPERSET_IRS_REPORTING_FOCUS_AREAS_COLUMNS = 'zambiaFocusArea2019';
export type SUPERSET_IRS_REPORTING_FOCUS_AREAS_COLUMNS = typeof SUPERSET_IRS_REPORTING_FOCUS_AREAS_COLUMNS;
export const SUPERSET_IRS_REPORTING_INDICATOR_STOPS = 'zambia2019';
export type SUPERSET_IRS_REPORTING_INDICATOR_STOPS = typeof SUPERSET_IRS_REPORTING_INDICATOR_STOPS;
export const SUPERSET_IRS_REPORTING_INDICATOR_ROWS = 'zambia2019';
export type SUPERSET_IRS_REPORTING_INDICATOR_ROWS = typeof SUPERSET_IRS_REPORTING_INDICATOR_ROWS;

export const SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_DATA_SLICES = '11,12';
export type SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_DATA_SLICES = typeof SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_DATA_SLICES;
export const SUPERSET_IRS_LITE_REPORTING_PLANS_SLICE = '13';
export type SUPERSET_IRS_LITE_REPORTING_PLANS_SLICE = typeof SUPERSET_IRS_LITE_REPORTING_PLANS_SLICE;
export const SUPERSET_IRS_LITE_REPORTING_STRUCTURES_DATA_SLICE = '14';
export type SUPERSET_IRS_LITE_REPORTING_STRUCTURES_DATA_SLICE = typeof SUPERSET_IRS_LITE_REPORTING_STRUCTURES_DATA_SLICE;
export const SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = '4';
export type SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = typeof SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL;
export const SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_COLUMNS = 'zambiaJurisdictions2019';
export type SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_COLUMNS = typeof SUPERSET_IRS_LITE_REPORTING_JURISDICTIONS_COLUMNS;
export const SUPERSET_IRS_LITE_REPORTING_FOCUS_AREAS_COLUMNS = 'zambiaFocusArea2019';
export type SUPERSET_IRS_LITE_REPORTING_FOCUS_AREAS_COLUMNS = typeof SUPERSET_IRS_LITE_REPORTING_FOCUS_AREAS_COLUMNS;
export const SUPERSET_IRS_LITE_REPORTING_INDICATOR_STOPS = 'zambia2019';
export type SUPERSET_IRS_LITE_REPORTING_INDICATOR_STOPS = typeof SUPERSET_IRS_LITE_REPORTING_INDICATOR_STOPS;
export const SUPERSET_IRS_LITE_REPORTING_INDICATOR_ROWS = 'zambia2019';
export type SUPERSET_IRS_LITE_REPORTING_INDICATOR_ROWS = typeof SUPERSET_IRS_LITE_REPORTING_INDICATOR_ROWS;

export const DATE_FORMAT = 'yyyy-MM-dd';
export type DATE_FORMAT = typeof DATE_FORMAT;

export const DEFAULT_TIME = 'T00:00:00+00:00';
export type DEFAULT_TIME = typeof DEFAULT_TIME;

export const DEFAULT_PLAN_DURATION_DAYS = 20;
export type DEFAULT_PLAN_DURATION_DAYS = typeof DEFAULT_PLAN_DURATION_DAYS;

export const DEFAULT_ACTIVITY_DURATION_DAYS = 7;
export type DEFAULT_ACTIVITY_DURATION_DAYS = typeof DEFAULT_ACTIVITY_DURATION_DAYS;

export const USERS_REQUEST_PAGE_SIZE = 51;
export type USERS_REQUEST_PAGE_SIZE = typeof USERS_REQUEST_PAGE_SIZE;

export const PRACTITIONER_REQUEST_PAGE_SIZE = 100;
export type PRACTITIONER_REQUEST_PAGE_SIZE = typeof PRACTITIONER_REQUEST_PAGE_SIZE;

export const LANGUAGE = 'en';
export type LANGUAGE = typeof LANGUAGE;

export const OAUTH_GET_STATE_URL = 'http://localhost:3000/oauth/state';
export type OAUTH_GET_STATE_URL = typeof OAUTH_GET_STATE_URL;

export const DISABLE_LOGIN_PROTECTION = false;

export const EXPRESS_OAUTH_GET_STATE_URL = 'http://localhost:3000/oauth/state';

export const EXPRESS_OAUTH_LOGOUT_URL = 'http://localhost:3000/logout';

export const BACKEND_ACTIVE = true;

export const SUPERSET_JURISDICTIONS_DATA_SLICE = 471;
export type SUPERSET_JURISDICTIONS_DATA_SLICE = typeof SUPERSET_JURISDICTIONS_DATA_SLICE;

export const SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_DATA_SLICES = '12,esw-jurisdictions';
export type SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_DATA_SLICES = typeof SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_DATA_SLICES;

export const SUPERSET_MDA_POINT_REPORTING_PLANS_SLICE = '01';
export type SUPERSET_MDA_POINT_REPORTING_PLANS_SLICE = typeof SUPERSET_MDA_POINT_REPORTING_PLANS_SLICE;

export const SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_COLUMNS = '0';
export type SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_COLUMNS = typeof SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_COLUMNS;

export const SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = '2';
export type SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = typeof SUPERSET_MDA_POINT_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL;

export const SUPERSET_MDA_POINT_REPORTING_FOCUS_AREAS_COLUMNS = '0';
export type SUPERSET_MDA_POINT_REPORTING_FOCUS_AREAS_COLUMNS = typeof SUPERSET_MDA_POINT_REPORTING_FOCUS_AREAS_COLUMNS;
export const REACT_APP_VERSION = 'v0.4.2';

export const DISPLAYED_PLAN_TYPES = ['FI', 'IRS', 'MDA', 'MDA-Point'];
export type DISPLAYED_PLAN_TYPES = typeof DISPLAYED_PLAN_TYPES;

export const PLAN_TYPES_ALLOWED_TO_CREATE = ['FI', 'IRS', 'MDA', 'MDA-Point', 'MDA-Lite'];
export type PLAN_TYPES_ALLOWED_TO_CREATE = typeof PLAN_TYPES_ALLOWED_TO_CREATE;

export const ENABLED_FI_REASONS = ['Case Triggered', 'Routine'];
export type ENABLED_FI_REASONS = typeof ENABLED_FI_REASONS;

export const WEBSITE_NAME = 'Reveal';

export const NAVBAR_BRAND_IMG_SRC =
  'https://github.com/onaio/reveal-frontend/raw/b0756b0c1ed95dc6db23dc4fd1375c81bdf7fb1b/src/assets/images/thai-logo.png';

export const REVEAL_BRAND_IMG_SRC =
  'https://github.com/onaio/reveal-frontend/raw/b0756b0c1ed95dc6db23dc4fd1375c81bdf7fb1b/src/assets/images/logo.png';

export const SUPERSET_MDA_POINT_LOCATION_REPORT_DATA_SLICE = '01';

export const SHOW_MDA_SCHOOL_REPORT_LABEL = true;

export const HIDDEN_MAP_LEGEND_ITEMS = [];

export const HIDDEN_PLAN_STATUSES = ['retired'];

export const ENABLE_JURISDICTIONS_AUTO_SELECTION = true;

export const ENABLE_JURISDICTION_AUTO_SELECTION_FOR_PLAN_TYPES = 'IRS,Dynamic-IRS'.split(',');

export const SUPERSET_DYNAMIC_MDA_REPORTING_PLANS_SLICE = '1337';
export const SUPERSET_DYNAMIC_MDA_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = '2';
export const SUPERSET_DYNAMIC_MDA_REPORTING_FOCUS_AREAS_COLUMNS = 'zambiaLowerUpper2020';
export const SUPERSET_DYNAMIC_MDA_REPORTING_JURISDICTIONS_COLUMNS = 'zambiaMDAUpper2020';
export const SUPERSET_DYNAMIC_MDA_REPORTING_JURISDICTIONS_DATA_SLICES = '1338';

export const ENABLED_JURISDICTION_METADATA_IDENTIFIER_OPTIONS = 'COVERAGE,POPULATION,RISK,STRUCTURE,TARGET'.split(
  ','
);

export const ASSIGNMENT_PAGE_SHOW_MAP = false;

export const MDA_POINT_FORM_INTERVENTION_TITLE = 'MDA_POINT_TITLE';
export const KEYCLOAK_LOGOUT_URL = 'https://keycloak/logout';

export const OPENSRP_LOGOUT_URL = 'https://opensrp/logout';

export const DOMAIN_NAME = 'localhost';

export const PLAN_TYPES_WITH_MULTI_JURISDICTIONS = [
  'IRS',
  'MDA-Point',
  'Dynamic-IRS',
  'Dynamic-MDA',
  'MDA-Lite',
];

export const SHOW_TEAM_ASSIGN_ON_OPERATIONAL_AREAS_ONLY = false;

// Menu items
export const ENABLE_ASSIGN = true;
export const ENABLE_IRS = true;
export const ENABLE_FI = true;
export const ENABLE_PRACTITIONERS = true;
export const ENABLE_USERS = false;
export const ENABLE_ABOUT = false;
export const ENABLE_TEAMS = true;
export const ENABLE_HOME_MANAGE_PLANS_LINK = true;
export const ENABLE_HOME_PLANNING_VIEW_LINK = true;
export const ENABLE_DEFAULT_PLAN_USER_FILTER = false;
export const ENABLE_IRS_MOPUP_REPORTING = true;
export const ENABLE_IRS_PERFORMANCE_REPORT = true;
export const ENABLE_IRS_LITE = true;
export const ENABLE_MDA_POINT = true;
export const ENABLE_DYNAMIC_MDA = true;

export const SUPERSET_IRS_MOPUP_REPORTING_JURISDICTIONS_DATA_SLICES = '200,201';
export const SUPERSET_IRS_MOPUP_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = '4';
export const SUPERSET_JURISDICTION_EVENTS_SLICE = '123';

export const SUPERSET_SMC_REPORTING_FOCUS_AREAS_COLUMNS = 'smcJurisdictionsColumns';
export const SUPERSET_SMC_REPORTING_JURISDICTIONS_COLUMNS = 'smcJurisdictionsColumns';
export const SUPERSET_SMC_REPORTING_JURISDICTIONS_FOCUS_AREA_LEVEL = '2';
export const SUPERSET_SMC_REPORTING_PLANS_SLICE = '1';
export const SUPERSET_SMC_REPORTING_JURISDICTIONS_DATA_SLICES = '5';
export const SUPERSET_SMC_REPORTING_STRUCTURES_DATA_SLICE = '9';
export const SUPERSET_SMC_REPORTING_INDICATOR_ROWS = 'nigeria2020';
export const SUPERSET_SMC_REPORTING_INDICATOR_STOPS = 'nigeria2020';

export const CHECK_SESSION_EXPIRY_STATUS = false;

export const OPENSRP_GENERATED_TASKS_INTERVENTIONS = [];
export const AUTO_SELECT_FI_CLASSIFICATION = false;
