/** Fixtures for tests */
export const data = [
  {
    adherence1: -1,
    adherence3: 4,
    adherence7: 0,
    canton: 'Canton 1',
    caseClass: 'Local',
    caseNotificationDate: '23/01/19',
    district: 'District 1',
    focusArea: 'Focus Area 1',
    id: 13,
    province: 'Province 1',
    status: 'A1',
    village: 'Village 1',
  },
  {
    adherence1: -1,
    adherence3: 1,
    adherence7: -5,
    canton: 'Canton 2',
    caseClass: 'Local',
    caseNotificationDate: '18/01/19',
    district: 'District 2',
    focusArea: 'Focus Area 2',
    id: 14,
    province: 'Province 2',
    status: 'A2',
    village: 'Village 2',
  },
  {
    adherence1: 2,
    adherence3: 2,
    adherence7: 4,
    canton: 'Canton 3',
    caseClass: 'Local',
    caseNotificationDate: '27/01/19',
    district: 'District 3',
    focusArea: 'Focus Area 3',
    id: 15,
    province: 'Province 3',
    status: 'A1',
    village: 'Village 3',
  },
  {
    adherence1: -1,
    adherence3: 0,
    adherence7: 6,
    canton: 'Canton 4',
    caseClass: 'Imported',
    caseNotificationDate: '29/01/19',
    district: 'District 4',
    focusArea: 'Focus Area 4',
    id: 16,
    province: 'Province 4',
    status: 'B1',
    village: 'Village 4',
  },
];
