/** Fixtures for tests */
import { keyBy } from 'lodash';

export const data = [
  {
    adherence1: -1,
    adherence3: 4,
    adherence7: 0,
    canton: 'Canton 1',
    caseClassification: 'Local',
    caseNotificationDate: '23/01/19',
    district: 'District 1',
    focusArea: 'Focus Area 1',
    id: '13',
    parent: null,
    province: 'Province 1',
    status: 'A1',
    village: 'Village 1',
  },
  {
    adherence1: -1,
    adherence3: 1,
    adherence7: -5,
    canton: 'Canton 2',
    caseClassification: 'Local',
    caseNotificationDate: '18/01/19',
    district: 'District 2',
    focusArea: 'Focus Area 2',
    id: '14',
    parent: null,
    province: 'Province 2',
    status: 'A2',
    village: 'Village 2',
  },
  {
    adherence1: 2,
    adherence3: 2,
    adherence7: 4,
    canton: 'Canton 3',
    caseClassification: 'Local',
    caseNotificationDate: '27/01/19',
    district: 'District 3',
    focusArea: 'Focus Area 3',
    id: '15',
    parent: null,
    province: 'Province 3',
    status: 'A1',
    village: 'Village 3',
  },
  {
    adherence1: -1,
    adherence3: 0,
    adherence7: 6,
    canton: 'Canton 4',
    caseClassification: 'Imported',
    caseNotificationDate: '29/01/19',
    district: 'District 4',
    focusArea: 'Focus Area 4',
    id: '16',
    parent: null,
    province: 'Province 4',
    status: 'B1',
    village: 'Village 4',
  },
  {
    adherence1: 999,
    adherence3: 999,
    adherence7: -999,
    canton: 'Canton 5 - this is a longer name than usual',
    caseClassification: 'Imported',
    caseNotificationDate: '29/01/19',
    district: 'District 5 - this is a longer name than usual',
    focusArea: 'Focus Area 5 - this is a longer name than usual',
    id: '17',
    parent: null,
    province: 'Province 5 - this is a longer name than usual',
    status: 'B1',
    village: 'Village 5 - this is a longer name than usual',
  },
];

export const dataIds = data.map(el => el.id);

export const dataByID = keyBy(data, 'id');

export const singleFI = dataByID['13'];
